# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Realm::Storage Realm::QueryParser Realm::ObjectStore Realm::RealmFFI Realm::RealmFFIStatic Realm::Sync)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Realm::Storage
add_library(Realm::Storage STATIC IMPORTED)

set_target_properties(Realm::Storage PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:Debug>:REALM_DEBUG=1>"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/dominic.frei/Repositories/RealmBootcamp/src;/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
  INTERFACE_LINK_OPTIONS "SHELL:-framework Foundation"
)

# Create imported target Realm::QueryParser
add_library(Realm::QueryParser STATIC IMPORTED)

set_target_properties(Realm::QueryParser PROPERTIES
  INTERFACE_LINK_LIBRARIES "Realm::Storage"
)

# Create imported target Realm::ObjectStore
add_library(Realm::ObjectStore STATIC IMPORTED)

set_target_properties(Realm::ObjectStore PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:Release>:NDEBUG>;\$<\$<CONFIG:RelWithDebInfo>:NDEBUG>;REALM_ENABLE_SYNC=1"
  INTERFACE_LINK_LIBRARIES "Realm::Storage;Realm::QueryParser;Realm::Sync"
)

# Create imported target Realm::RealmFFI
add_library(Realm::RealmFFI SHARED IMPORTED)

set_target_properties(Realm::RealmFFI PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/dominic.frei/Repositories/RealmBootcamp/src"
)

# Create imported target Realm::RealmFFIStatic
add_library(Realm::RealmFFIStatic STATIC IMPORTED)

set_target_properties(Realm::RealmFFIStatic PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "RLM_NO_DLLIMPORT"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/dominic.frei/Repositories/RealmBootcamp/src"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Realm::Storage>;\$<LINK_ONLY:Realm::ObjectStore>;\$<LINK_ONLY:Realm::QueryParser>;\$<LINK_ONLY:Realm::Sync>"
)

# Create imported target Realm::Sync
add_library(Realm::Sync STATIC IMPORTED)

set_target_properties(Realm::Sync PROPERTIES
  INTERFACE_LINK_LIBRARIES "Realm::Storage"
  INTERFACE_LINK_OPTIONS "-lz;SHELL:-framework Security"
)

# Import target "Realm::Storage" for configuration "Debug"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/Debug/librealm-dbg.a"
  )

# Import target "Realm::QueryParser" for configuration "Debug"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/parser/Debug/librealm-parser-dbg.a"
  )

# Import target "Realm::ObjectStore" for configuration "Debug"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/Debug/librealm-object-store-dbg.a"
  )

# Import target "Realm::RealmFFI" for configuration "Debug"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/Debug/librealm-ffi-dbg.dylib"
  IMPORTED_SONAME_DEBUG "@rpath/librealm-ffi-dbg.dylib"
  )

# Import target "Realm::RealmFFIStatic" for configuration "Debug"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/Debug/librealm-ffi-static-dbg.a"
  )

# Import target "Realm::Sync" for configuration "Debug"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/sync/Debug/librealm-sync-dbg.a"
  )

# Import target "Realm::Storage" for configuration "Release"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/Release/librealm.a"
  )

# Import target "Realm::QueryParser" for configuration "Release"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/parser/Release/librealm-parser.a"
  )

# Import target "Realm::ObjectStore" for configuration "Release"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/Release/librealm-object-store.a"
  )

# Import target "Realm::RealmFFI" for configuration "Release"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/Release/librealm-ffi.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/librealm-ffi.dylib"
  )

# Import target "Realm::RealmFFIStatic" for configuration "Release"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/Release/librealm-ffi-static.a"
  )

# Import target "Realm::Sync" for configuration "Release"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/sync/Release/librealm-sync.a"
  )

# Import target "Realm::Storage" for configuration "MinSizeRel"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/MinSizeRel/librealm.a"
  )

# Import target "Realm::QueryParser" for configuration "MinSizeRel"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/parser/MinSizeRel/librealm-parser.a"
  )

# Import target "Realm::ObjectStore" for configuration "MinSizeRel"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/MinSizeRel/librealm-object-store.a"
  )

# Import target "Realm::RealmFFI" for configuration "MinSizeRel"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/MinSizeRel/librealm-ffi.dylib"
  IMPORTED_SONAME_MINSIZEREL "@rpath/librealm-ffi.dylib"
  )

# Import target "Realm::RealmFFIStatic" for configuration "MinSizeRel"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/MinSizeRel/librealm-ffi-static.a"
  )

# Import target "Realm::Sync" for configuration "MinSizeRel"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/sync/MinSizeRel/librealm-sync.a"
  )

# Import target "Realm::Storage" for configuration "RelWithDebInfo"
set_property(TARGET Realm::Storage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::Storage PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/RelWithDebInfo/librealm.a"
  )

# Import target "Realm::QueryParser" for configuration "RelWithDebInfo"
set_property(TARGET Realm::QueryParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::QueryParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/parser/RelWithDebInfo/librealm-parser.a"
  )

# Import target "Realm::ObjectStore" for configuration "RelWithDebInfo"
set_property(TARGET Realm::ObjectStore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::ObjectStore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/RelWithDebInfo/librealm-object-store.a"
  )

# Import target "Realm::RealmFFI" for configuration "RelWithDebInfo"
set_property(TARGET Realm::RealmFFI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::RealmFFI PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/RelWithDebInfo/librealm-ffi.dylib"
  IMPORTED_SONAME_RELWITHDEBINFO "@rpath/librealm-ffi.dylib"
  )

# Import target "Realm::RealmFFIStatic" for configuration "RelWithDebInfo"
set_property(TARGET Realm::RealmFFIStatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::RealmFFIStatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/object-store/c_api/RelWithDebInfo/librealm-ffi-static.a"
  )

# Import target "Realm::Sync" for configuration "RelWithDebInfo"
set_property(TARGET Realm::Sync APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Realm::Sync PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dominic.frei/Repositories/RealmBootcamp/build.debug/src/realm/sync/RelWithDebInfo/librealm-sync.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
